---
title: "mental-health-cost"
author: "Yingjie"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(stringr)
library(ggplot2)
require(scales) # to access break formatting functions


dir.cost <- './data/cost/'

today <- format(Sys.time(), "%Y%m%d"); today
```


## data

  source: https://ncrr-au.shinyapps.io/mental-cost/
  Christensen MK et al (2020). The cost of mental disorders: a systematic review. Epidemiology and Psychiatric Sciences 29, e161, 1–8. https://doi.org/10.1017/ S204579602000075X
  
```{r}
f <- paste0(dir.cost, 'Christensen_et_al_2020/', 'data-full.xlsx') # simplified data shared online 
# f <- paste0(dir.cost, 'Christensen_et_al_2020/', '200205_SR.xlsx') # detailed data shared by John McGrath


d <- readxl::read_excel(f, col_types = "text") %>%
  rename('Price_2018_adj' = '2018_Price (inflation adjusted)')

names(d)
unique(d$dx_broad) %>% sort()


unique(d$cost_broad_type)
unique(d$cost_type)
unique(d$cost_unit)


## select data for later use
cost_broad_type_i <- "total societal cost"
cost_unit_i       <- "mean cost per patient"


## check the data
d_check <- d %>%
  filter(cost_broad_type == cost_broad_type_i,
         cost_unit == cost_unit_i) %>%
  as.data.frame()

##' NOTE: there are multiple rows even after specify a cost type and unit, this is because there are 
##'   more detailed mental disorder sub-classifications, which are not included in the shared data "data-full.xlsx". 
##' NEW: The detailed data "200205_SR.xlsx" shared by John McGrath has more information. 




## filter data
df <- d %>%
  filter(!dx_broad %in% c("any mental disorder"), 
         str_detect(dx_broad, ',', negate = T),
         cost_broad_type == cost_broad_type_i,
         cost_unit == cost_unit_i) %>%
  # filter(!is.na(Price_USD_PPP)) %>%
  # select(1:cost_type, 
  #        # Price_USD, 
  #        # Price_USD_PPP, 
  #        Price_2018_adj,
  #        -c(study_title, site, cost_specific_type)) %>%
  mutate(Price_USD_PPP = as.numeric(Price_USD_PPP),
         Price_2018_adj = as.numeric(Price_2018_adj)) %>%
  select(1:cost_type, everything())
  

unique(df$dx_broad) %>% sort() %>%
  paste(., collapse = ', ') %>%
  cat('\nUnique mental health indicators:\n', .)

unique(df$dx_type) %>% sort() #%>%
  # paste(., collapse = ', ') %>%
  # cat('\nUnique mental health indicators:\n', .)


cat('\n Unique countries:', length(unique(df$country)))
```


```{r - plot as Christensen}


df_ctr_dx <- df %>%
  group_by(country, dx_broad, cost_broad_type, cost_unit) %>%
  summarise_at(c('Price_USD', 'Price_USD_PPP', 'Price_2018_adj'), mean, na.rm = TRUE) %>%
  as.data.frame()

n_dx <- length(unique(df_ctr_dx$dx_broad))


df_ctr_dx %>%
  filter(cost_broad_type == cost_broad_type_i) %>%
  ggplot(aes(y = country, x = Price_USD_PPP)) + 
  geom_point(
    alpha = 0.8,
    aes(
      colour = dx_broad,
      shape = dx_broad)) +
  scale_shape_manual(values = c(seq(1:6), 15, 16, 17) ) +
  scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  scale_y_discrete(limits=rev) +
  xlab('Societal cost per patient in USD PPP 2018') +
  theme_bw()

f <- paste0('./figures/', 'mental_cost_', today, '.png'); f
ggsave(f, plot = last_plot(), width = 7, height = 7, units = 'in', dpi = 300, bg = NULL)
```



```{r - relevant to InVEST}
df_select <- df_ctr_dx %>%
  filter(dx_broad %in% c("behavioural disorders", 
                         "mood disorders", 
                         # "personality disorders", 
                         "schizophrenia")) %>%
  as.data.frame() 



df_mood <- df_select %>%
  filter(dx_broad == "mood disorders") %>%
  select(-c(Price_USD, Price_2018_adj)) %>%
  mutate(year = 2018) %>%
  as.data.frame()


## save data in csv
f <- paste0(dir.cost, 'data_cost_mental_health.csv'); f
readr::write_csv(df_mood, f)

```



```{r - relevant to InVEST}
df_select %>%
  ggplot(aes(y = country, x = Price_USD_PPP)) + 
  geom_point(
    alpha = 0.8,
    aes(
      colour = dx_broad,
      shape = dx_broad)) +
  scale_shape_manual(values = c(seq(1:6), 15, 16, 17) ) +
  scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  scale_y_discrete(limits=rev) +
  xlab('Societal cost per patient in USD PPP 2018') +
  theme_bw()

ggsave(filename = './figures/mental_cost_select_2.png', plot = last_plot(), width = 7, height = 7, units = 'in', dpi = 300, bg = NULL)
```

