"""
cities.py — 487 US cities with state codes and official domains.
"""

from dataclasses import dataclass
from typing import List, Optional


@dataclass
class City:
    name: str
    state: str
    domains: List[str]
    aliases: Optional[List[str]] = None

    @property
    def key(self) -> str:
        """Unique key for DB / lookup: 'city, ST'."""
        return f"{self.name}, {self.state}"

    @property
    def primary_domain(self) -> str:
        return self.domains[0] if self.domains else ""


# fmt: off
CITIES: List[City] = [
    # ── Alabama ──
    City("Huntsville",              "AL", ["huntsvilleal.gov"]),
    # ── Arkansas ──
    City("Little Rock",             "AR", ["littlerock.gov"]),
    # ── Arizona ──
    City("Chandler",                "AZ", ["chandleraz.gov"]),
    City("Gilbert",                 "AZ", ["gilbertaz.gov"]),
    City("Glendale",                "AZ", ["glendaleaz.com"]),
    City("Mesa",                    "AZ", ["mesaaz.gov"]),
    City("Phoenix",                 "AZ", ["phoenix.gov"]),
    City("Tempe",                   "AZ", ["tempe.gov"]),
    # ── California ──
    City("Alameda",                 "CA", []),
    City("Alhambra",                "CA", []),
    City("Aliso Viejo",             "CA", []),
    City("Anaheim",                 "CA", ["anaheim.net"]),
    City("Antioch",                 "CA", []),
    City("Arcadia",                 "CA", []),
    City("Azusa",                   "CA", []),
    City("Bakersfield",             "CA", ["bakersfieldcity.us"]),
    City("Baldwin Park",            "CA", []),
    City("Bellflower",              "CA", []),
    City("Berkeley",                "CA", []),
    City("Brentwood",               "CA", []),
    City("Buena Park",              "CA", []),
    City("Burbank",                 "CA", []),
    City("Camarillo",               "CA", []),
    City("Carlsbad",                "CA", []),
    City("Carson",                  "CA", []),
    City("Chico",                   "CA", []),
    City("Chino",                   "CA", []),
    City("Chula Vista",             "CA", ["chulavistaca.gov"]),
    City("Citrus Heights",          "CA", []),
    City("Clovis",                  "CA", []),
    City("Colton",                  "CA", []),
    City("Compton",                 "CA", []),
    City("Concord",                 "CA", []),
    City("Corona",                  "CA", []),
    City("Costa Mesa",              "CA", []),
    City("Covina",                  "CA", []),
    City("Cupertino",               "CA", []),
    City("Cypress",                 "CA", []),
    City("Daly City",               "CA", []),
    City("Davis",                   "CA", []),
    City("Diamond Bar",             "CA", []),
    City("Downey",                  "CA", []),
    City("Dublin",                  "CA", []),
    City("Eastvale",                "CA", []),
    City("El Cajon",                "CA", []),
    City("El Monte",                "CA", []),
    City("Elk Grove",               "CA", ["elkgrovecity.org"]),
    City("Encinitas",               "CA", []),
    City("Escondido",               "CA", []),
    City("Fairfield",               "CA", []),
    City("Folsom",                  "CA", []),
    City("Fontana",                 "CA", ["fontana.org"]),
    City("Fountain Valley",         "CA", []),
    City("Fremont",                 "CA", ["fremont.gov"]),
    City("Fresno",                  "CA", ["fresno.gov"]),
    City("Fullerton",               "CA", []),
    City("Garden Grove",            "CA", []),
    City("Gardena",                 "CA", []),
    City("Gilroy",                  "CA", []),
    City("Glendale",                "CA", ["glendaleca.gov"]),
    City("Glendora",                "CA", []),
    City("Hanford",                 "CA", []),
    City("Hawthorne",               "CA", []),
    City("Hayward",                 "CA", []),
    City("Hemet",                   "CA", []),
    City("Highland",                "CA", []),
    City("Huntington Beach",        "CA", ["huntingtonbeachca.gov"]),
    City("Huntington Park",         "CA", []),
    City("Indio",                   "CA", []),
    City("Inglewood",               "CA", []),
    City("Irvine",                  "CA", ["cityofirvine.org"]),
    City("La Habra",                "CA", []),
    City("La Mesa",                 "CA", []),
    City("Laguna Niguel",           "CA", []),
    City("Lake Forest",             "CA", []),
    City("Lakewood",                "CA", []),
    City("Livermore",               "CA", []),
    City("Lodi",                    "CA", []),
    City("Long Beach",              "CA", ["longbeach.gov"]),
    City("Los Angeles",             "CA", ["lacity.gov", "lacity.org"]),
    City("Lynwood",                 "CA", []),
    City("Madera",                  "CA", []),
    City("Manteca",                 "CA", []),
    City("Merced",                  "CA", []),
    City("Milpitas",                "CA", []),
    City("Mission Viejo",           "CA", []),
    City("Modesto",                 "CA", ["modestogov.com"]),
    City("Montebello",              "CA", []),
    City("Monterey Park",           "CA", []),
    City("Moreno Valley",           "CA", ["moval.org"]),
    City("Mountain View",           "CA", []),
    City("Murrieta",                "CA", []),
    City("Napa",                    "CA", []),
    City("National City",           "CA", []),
    City("Newport Beach",           "CA", []),
    City("Norwalk",                 "CA", []),
    City("Oakland",                 "CA", ["oaklandca.gov"]),
    City("Oceanside",               "CA", []),
    City("Ontario",                 "CA", ["ontarioca.gov"]),
    City("Orange",                  "CA", []),
    City("Oxnard",                  "CA", ["oxnard.org"]),
    City("Palo Alto",               "CA", []),
    City("Paramount",               "CA", []),
    City("Pasadena",                "CA", []),
    City("Petaluma",                "CA", []),
    City("Pico Rivera",             "CA", []),
    City("Pittsburg",               "CA", []),
    City("Placentia",               "CA", []),
    City("Pleasanton",              "CA", []),
    City("Pomona",                  "CA", []),
    City("Porterville",             "CA", []),
    City("Rancho Cucamonga",        "CA", []),
    City("Redondo Beach",           "CA", []),
    City("Redwood City",            "CA", []),
    City("Rialto",                  "CA", []),
    City("Richmond",                "CA", []),
    City("Riverside",               "CA", ["riversideca.gov"]),
    City("Rocklin",                 "CA", []),
    City("Rosemead",                "CA", []),
    City("Roseville",               "CA", []),
    City("Sacramento",              "CA", ["cityofsacramento.org"]),
    City("Salinas",                 "CA", []),
    City("San Bernardino",          "CA", ["sbcity.org"]),
    City("San Buenaventura (Ventura)", "CA", []),
    City("San Clemente",            "CA", []),
    City("San Diego",               "CA", ["sandiego.gov"]),
    City("San Francisco",           "CA", ["sf.gov", "sfgov.org"]),
    City("San Jose",                "CA", ["sanjoseca.gov"]),
    City("San Leandro",             "CA", []),
    City("San Marcos",              "CA", []),
    City("San Mateo",               "CA", []),
    City("San Rafael",              "CA", []),
    City("San Ramon",               "CA", []),
    City("Santa Ana",               "CA", ["santa-ana.org"]),
    City("Santa Barbara",           "CA", []),
    City("Santa Clara",             "CA", []),
    City("Santa Clarita",           "CA", ["santa-clarita.com"]),
    City("Santa Cruz",              "CA", []),
    City("Santa Maria",             "CA", []),
    City("Santa Monica",            "CA", []),
    City("Santa Rosa",              "CA", []),
    City("Santee",                  "CA", []),
    City("Simi Valley",             "CA", []),
    City("South Gate",              "CA", []),
    City("South San Francisco",     "CA", []),
    City("Stockton",                "CA", ["stocktonca.gov"]),
    City("Sunnyvale",               "CA", []),
    City("Temecula",                "CA", []),
    City("Torrance",                "CA", []),
    City("Tracy",                   "CA", []),
    City("Tulare",                  "CA", []),
    City("Turlock",                 "CA", []),
    City("Tustin",                  "CA", []),
    City("Union City",              "CA", []),
    City("Upland",                  "CA", []),
    City("Vacaville",               "CA", []),
    City("Vallejo",                 "CA", []),
    City("Visalia",                 "CA", []),
    City("Vista",                   "CA", []),
    City("Walnut Creek",            "CA", []),
    City("Watsonville",             "CA", []),
    City("West Covina",             "CA", []),
    City("Westminster",             "CA", []),
    City("Whittier",                "CA", []),
    City("Woodland",                "CA", []),
    City("Yorba Linda",             "CA", []),
    City("Yuba City",               "CA", []),
    # ── Colorado ──
    City("Arvada",                  "CO", []),
    City("Boulder",                 "CO", []),
    City("Centennial",              "CO", []),
    City("Denver",                  "CO", ["denvergov.org"]),
    City("Fort Collins",            "CO", []),
    City("Lakewood",                "CO", []),
    City("Longmont",                "CO", []),
    City("Parker",                  "CO", []),
    City("Thornton",                "CO", []),
    City("Westminster",             "CO", []),
    # ── Connecticut ──
    City("Bridgeport",              "CT", []),
    City("Hartford",                "CT", []),
    City("New Britain",             "CT", []),
    City("New Haven",               "CT", []),
    City("Norwalk",                 "CT", []),
    City("Stamford",                "CT", []),
    City("Waterbury",               "CT", []),
    City("West Haven",              "CT", []),
    # ── District of Columbia ──
    City("Washington",              "DC", ["dc.gov"]),
    # ── Delaware ──
    City("Wilmington",              "DE", []),
    # ── Florida ──
    City("Boca Raton",              "FL", []),
    City("Boynton Beach",           "FL", []),
    City("Bradenton",               "FL", []),
    City("Coconut Creek",           "FL", []),
    City("Coral Springs",           "FL", []),
    City("Davie",                   "FL", []),
    City("Deerfield Beach",         "FL", []),
    City("Delray Beach",            "FL", []),
    City("Doral",                   "FL", []),
    City("Fort Lauderdale",         "FL", ["fortlauderdale.gov"]),
    City("Hialeah",                 "FL", ["hialeahfl.gov"]),
    City("Hollywood",               "FL", []),
    City("Homestead",               "FL", []),
    City("Jupiter",                 "FL", []),
    City("Kissimmee",               "FL", []),
    City("Lauderhill",              "FL", []),
    City("Margate",                 "FL", []),
    City("Miami",                   "FL", ["miamigov.com"]),
    City("Miami Beach",             "FL", []),
    City("Miami Gardens",           "FL", []),
    City("Miramar",                 "FL", []),
    City("North Miami",             "FL", []),
    City("Orlando",                 "FL", ["orlando.gov"]),
    City("Pembroke Pines",          "FL", []),
    City("Plantation",              "FL", []),
    City("Pompano Beach",           "FL", []),
    City("Sanford",                 "FL", []),
    City("Sarasota",                "FL", []),
    City("Sunrise",                 "FL", []),
    City("Tamarac",                 "FL", []),
    City("Weston",                  "FL", []),
    # ── Georgia ──
    City("Atlanta",                 "GA", []),
    # ── Iowa ──
    City("Iowa City",               "IA", []),
    # ── Idaho ──
    City("Boise City",              "ID", ["cityofboise.org"]),
    City("Caldwell",                "ID", []),
    City("Coeur d'Alene",           "ID", []),
    City("Idaho Falls",             "ID", []),
    City("Meridian",                "ID", []),
    City("Nampa",                   "ID", []),
    City("Twin Falls",              "ID", []),
    # ── Illinois ──
    City("Arlington Heights",       "IL", []),
    City("Aurora",                  "IL", ["aurora-il.org"]),
    City("Berwyn",                  "IL", []),
    City("Bloomington",             "IL", []),
    City("Bolingbrook",             "IL", []),
    City("Champaign",               "IL", []),
    City("Chicago",                 "IL", ["chicago.gov"]),
    City("Cicero",                  "IL", []),
    City("Des Plaines",             "IL", []),
    City("Downers Grove",           "IL", []),
    City("Elgin",                   "IL", []),
    City("Evanston",                "IL", []),
    City("Mount Prospect",          "IL", []),
    City("Naperville",              "IL", []),
    City("Normal",                  "IL", []),
    City("Oak Lawn",                "IL", []),
    City("Oak Park",                "IL", []),
    City("Orland Park",             "IL", []),
    City("Palatine",                "IL", []),
    City("Schaumburg",              "IL", []),
    City("Skokie",                  "IL", []),
    City("Tinley Park",             "IL", []),
    City("Waukegan",                "IL", []),
    City("Wheaton",                 "IL", []),
    # ── Indiana ──
    City("Bloomington",             "IN", []),
    City("Fishers",                 "IN", []),
    City("Hammond",                 "IN", []),
    City("Mishawaka",               "IN", []),
    # ── Kansas ──
    City("Lawrence",                "KS", []),
    City("Manhattan",               "KS", []),
    City("Overland Park",           "KS", ["opkansas.org"]),
    # ── Kentucky ──
    City("Owensboro",               "KY", []),
    # ── Louisiana ──
    City("Baton Rouge",             "LA", ["brla.gov"]),
    City("Kenner",                  "LA", []),
    # ── Massachusetts ──
    City("Boston",                  "MA", ["boston.gov"]),
    City("Brockton",                "MA", []),
    City("Cambridge",               "MA", []),
    City("Fall River",              "MA", []),
    City("Framingham",              "MA", []),
    City("Lawrence",                "MA", []),
    City("Lowell",                  "MA", []),
    City("Lynn",                    "MA", []),
    City("Malden",                  "MA", []),
    City("Medford",                 "MA", []),
    City("New Bedford",             "MA", []),
    City("Newton",                  "MA", []),
    City("Peabody",                 "MA", []),
    City("Quincy",                  "MA", []),
    City("Revere",                  "MA", []),
    City("Somerville",              "MA", []),
    City("Springfield",             "MA", []),
    City("Waltham",                 "MA", []),
    City("Weymouth Town",           "MA", []),
    City("Worcester",               "MA", ["worcesterma.gov"]),
    # ── Maryland ──
    City("Baltimore",               "MD", ["baltimorecity.gov"]),
    City("Bowie",                   "MD", []),
    City("Frederick",               "MD", []),
    City("Gaithersburg",            "MD", []),
    City("Rockville",               "MD", []),
    # ── Maine ──
    City("Portland",                "ME", []),
    # ── Michigan ──
    City("Ann Arbor",               "MI", []),
    City("Dearborn",                "MI", []),
    City("Dearborn Heights",        "MI", []),
    City("Detroit",                 "MI", ["detroitmi.gov"]),
    City("Grand Rapids",            "MI", ["grandrapidsmi.gov"]),
    City("Kalamazoo",               "MI", []),
    City("Kentwood",                "MI", []),
    City("Lansing",                 "MI", []),
    City("Livonia",                 "MI", []),
    City("Pontiac",                 "MI", []),
    City("Royal Oak",               "MI", []),
    City("Southfield",              "MI", []),
    City("St. Clair Shores",        "MI", []),
    City("Sterling Heights",        "MI", []),
    City("Taylor",                  "MI", []),
    City("Troy",                    "MI", []),
    City("Warren",                  "MI", []),
    City("Westland",                "MI", []),
    City("Wyoming",                 "MI", []),
    # ── Minnesota ──
    City("Apple Valley",            "MN", []),
    City("Brooklyn Park",           "MN", []),
    City("Coon Rapids",             "MN", []),
    City("Edina",                   "MN", []),
    City("Minneapolis",             "MN", ["minneapolismn.gov"]),
    City("St. Louis Park",          "MN", []),
    City("St. Paul",                "MN", ["stpaul.gov"]),
    # ── Missouri ──
    City("Blue Springs",            "MO", []),
    City("Florissant",              "MO", []),
    City("O'Fallon",                "MO", []),
    City("St. Charles",             "MO", []),
    City("St. Louis",               "MO", ["stlouis-mo.gov"]),
    # ── Mississippi ──
    City("Jackson",                 "MS", []),
    # ── Montana ──
    City("Billings",                "MT", []),
    City("Great Falls",             "MT", []),
    # ── North Carolina ──
    City("Apex",                    "NC", []),
    City("Cary",                    "NC", ["townofcary.org"]),
    City("Chapel Hill",             "NC", []),
    City("Charlotte",               "NC", ["charlottenc.gov"]),
    City("Raleigh",                 "NC", ["raleighnc.gov"]),
    # ── North Dakota ──
    City("Fargo",                   "ND", []),
    # ── Nebraska ──
    City("Bellevue",                "NE", []),
    City("Lincoln",                 "NE", ["lincoln.ne.gov"]),
    City("Omaha",                   "NE", ["cityofomaha.org"]),
    # ── New Hampshire ──
    City("Manchester",              "NH", []),
    City("Nashua",                  "NH", []),
    # ── New Jersey ──
    City("Bayonne",                 "NJ", []),
    City("Camden",                  "NJ", []),
    City("Clifton",                 "NJ", []),
    City("East Orange",             "NJ", []),
    City("Elizabeth",               "NJ", []),
    City("Hoboken",                 "NJ", []),
    City("Jersey City",             "NJ", ["jerseycitynj.gov"]),
    City("New Brunswick",           "NJ", []),
    City("Newark",                  "NJ", ["newarknj.gov"]),
    City("Passaic",                 "NJ", []),
    City("Paterson",                "NJ", []),
    City("Perth Amboy",             "NJ", []),
    City("Plainfield",              "NJ", []),
    City("Trenton",                 "NJ", []),
    City("Union City",              "NJ", []),
    City("West New York",           "NJ", []),
    # ── New Mexico ──
    City("Albuquerque",             "NM", ["cabq.gov"]),
    # ── Nevada ──
    City("Henderson",               "NV", ["cityofhenderson.com"]),
    City("Las Vegas",               "NV", ["lasvegasnevada.gov"]),
    City("Sparks",                  "NV", []),
    # ── New York ──
    City("Albany",                  "NY", []),
    City("Buffalo",                 "NY", ["buffalony.gov"]),
    City("Hempstead",               "NY", []),
    City("Mount Vernon",            "NY", []),
    City("New Rochelle",            "NY", []),
    City("New York",                "NY", ["nyc.gov"], aliases=["NYC"]),
    City("Rochester",               "NY", ["cityofrochester.gov"]),
    City("Schenectady",             "NY", []),
    City("Syracuse",                "NY", []),
    City("Troy",                    "NY", []),
    City("Utica",                   "NY", []),
    City("White Plains",            "NY", []),
    City("Yonkers",                 "NY", ["yonkersny.gov"]),
    # ── Ohio ──
    City("Akron",                   "OH", ["akronohio.gov"]),
    City("Canton",                  "OH", []),
    City("Cincinnati",              "OH", ["cincinnati-oh.gov"]),
    City("Cleveland",               "OH", ["clevelandohio.gov"]),
    City("Columbus",                "OH", ["columbus.gov"]),
    City("Hamilton",                "OH", []),
    City("Kettering",               "OH", []),
    City("Lakewood",                "OH", []),
    City("Lorain",                  "OH", []),
    City("Parma",                   "OH", []),
    City("Toledo",                  "OH", ["toledo.oh.gov"]),
    # ── Oklahoma ──
    City("Moore",                   "OK", []),
    # ── Oregon ──
    City("Albany",                  "OR", []),
    City("Beaverton",               "OR", []),
    City("Bend",                    "OR", []),
    City("Corvallis",               "OR", []),
    City("Eugene",                  "OR", []),
    City("Gresham",                 "OR", []),
    City("Hillsboro",               "OR", []),
    City("Medford",                 "OR", []),
    City("Portland",                "OR", ["portland.gov"]),
    City("Salem",                   "OR", []),
    City("Springfield",             "OR", []),
    City("Tigard",                  "OR", []),
    # ── Pennsylvania ──
    City("Allentown",               "PA", []),
    City("Bethlehem",               "PA", []),
    City("Erie",                    "PA", []),
    City("Harrisburg",              "PA", []),
    City("Lancaster",               "PA", []),
    City("Philadelphia",            "PA", ["phila.gov"]),
    City("Pittsburgh",              "PA", ["pittsburghpa.gov"]),
    City("Reading",                 "PA", []),
    City("Scranton",                "PA", []),
    # ── Rhode Island ──
    City("Cranston",                "RI", []),
    City("Pawtucket",               "RI", []),
    City("Providence",              "RI", ["providenceri.gov"]),
    # ── South Carolina ──
    City("Charleston",              "SC", []),
    # ── South Dakota ──
    City("Sioux Falls",             "SD", ["siouxfalls.org"]),
    # ── Tennessee ──
    City("Nashville-Davidson",      "TN", ["nashville.gov"]),
    # ── Texas ──
    City("Allen",                   "TX", []),
    City("Arlington",               "TX", ["arlingtontx.gov"]),
    City("Austin",                  "TX", ["austintexas.gov"]),
    City("Carrollton",              "TX", []),
    City("Cedar Park",              "TX", []),
    City("Dallas",                  "TX", ["dallascityhall.com", "dallascityhall.org"]),
    City("DeSoto",                  "TX", []),
    City("El Paso",                 "TX", ["elpasotexas.gov"]),
    City("Euless",                  "TX", []),
    City("Fort Worth",              "TX", ["fortworthtexas.gov"]),
    City("Frisco",                  "TX", ["friscotexas.gov"]),
    City("Garland",                 "TX", ["garlandtx.gov"]),
    City("Grand Prairie",           "TX", ["gptx.org"]),
    City("Houston",                 "TX", ["houstontx.gov"]),
    City("Irving",                  "TX", ["cityofirving.org"]),
    City("Killeen",                 "TX", []),
    City("Lewisville",              "TX", []),
    City("McKinney",                "TX", ["mckinneytexas.org"]),
    City("Mesquite",                "TX", []),
    City("North Richland Hills",    "TX", []),
    City("Pasadena",                "TX", []),
    City("Pharr",                   "TX", []),
    City("Plano",                   "TX", ["plano.gov"]),
    City("Richardson",              "TX", []),
    City("Round Rock",              "TX", []),
    City("Rowlett",                 "TX", []),
    City("San Antonio",             "TX", ["sanantonio.gov"]),
    City("Sugar Land",              "TX", []),
    City("Wylie",                   "TX", []),
    # ── Utah ──
    City("Herriman",                "UT", []),
    City("Layton",                  "UT", []),
    City("Lehi",                    "UT", []),
    City("Logan",                   "UT", []),
    City("Millcreek",               "UT", []),
    City("Murray",                  "UT", []),
    City("Ogden",                   "UT", []),
    City("Orem",                    "UT", []),
    City("Provo",                   "UT", []),
    City("Sandy",                   "UT", []),
    City("South Jordan",            "UT", []),
    City("Taylorsville",            "UT", []),
    City("West Jordan",             "UT", []),
    City("West Valley City",        "UT", []),
    # ── Virginia ──
    City("Alexandria",              "VA", []),
    City("Hampton",                 "VA", []),
    City("Harrisonburg",            "VA", []),
    City("Newport News",            "VA", ["nnva.gov"]),
    City("Norfolk",                 "VA", ["norfolk.gov"]),
    City("Portsmouth",              "VA", []),
    City("Richmond",                "VA", ["rva.gov"]),
    # ── Vermont ──
    City("Burlington",              "VT", []),
    # ── Washington ──
    City("Auburn",                  "WA", []),
    City("Bellevue",                "WA", []),
    City("Bellingham",              "WA", []),
    City("Burien",                  "WA", []),
    City("Everett",                 "WA", []),
    City("Federal Way",             "WA", []),
    City("Kennewick",               "WA", []),
    City("Kent",                    "WA", []),
    City("Kirkland",                "WA", []),
    City("Lacey",                   "WA", []),
    City("Lakewood",                "WA", []),
    City("Marysville",              "WA", []),
    City("Olympia",                 "WA", []),
    City("Redmond",                 "WA", []),
    City("Renton",                  "WA", []),
    City("Sammamish",               "WA", []),
    City("Seattle",                 "WA", ["seattle.gov"]),
    City("Shoreline",               "WA", []),
    City("Spokane",                 "WA", ["spokanecity.org"]),
    City("Spokane Valley",          "WA", []),
    City("Tacoma",                  "WA", ["cityoftacoma.org"]),
    City("Vancouver",               "WA", ["cityofvancouver.us"]),
    City("Yakima",                  "WA", []),
    # ── Wisconsin ──
    City("Appleton",                "WI", []),
    City("Kenosha",                 "WI", []),
    City("Madison",                 "WI", ["cityofmadison.com"]),
    City("Milwaukee",               "WI", ["city.milwaukee.gov"]),
    City("Racine",                  "WI", []),
    City("Waukesha",                "WI", []),
    City("West Allis",              "WI", []),
    # ── West Virginia ──
    City("Charleston",              "WV", []),
    # ── Wyoming ──
    City("Cheyenne",                "WY", []),
]
# fmt: on


def get_city(name: str, state: str) -> City | None:
    """Look up a city by name and state code."""
    for c in CITIES:
        if c.name.lower() == name.lower() and c.state.upper() == state.upper():
            return c
    return None


def get_all_cities() -> List[City]:
    """Return full city list."""
    return CITIES
